running
  '/opt/apps/intel18/impi18_0/Rstats/3.5.1/lib64/R/bin/R --slave --no-restore --file=./MainvQTLcode.R'

During startup - Warning message:
Setting LC_CTYPE failed, using "C" 

Attaching package: 'vqtl'

The following object is masked from 'package:qtl':

    scanonevar


Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
<U+221A> ggplot2 3.0.0     <U+221A> tidyr   0.8.1
<U+221A> tibble  2.1.3     <U+221A> stringr 1.3.1
<U+221A> ggplot2 3.0.0     <U+221A> forcats 0.3.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Warning messages:
1: In if (format == "csvrs") { :
  the condition has length > 1 and only the first element will be used
2: In read.cross.csv(dir, file, na.strings, genotypes, estimate.map,  :
  The following unexpected genotype codes were treated as missing.
    |?|B}|

3: In summary.cross(cross) : Strange genotype pattern.
4: In summary.cross(cross) :
  Some chromosomes > 1000 cM in length; there may be a problem with the genetic map.
  (Perhaps it is in basepairs?)
Error in validate.scanonevar.input_(cross = cross, mean.formula = mean.formula,  : 
  formulae_is_valid_(formulae = formulae) is not TRUE
Calls: scanonevar -> validate.scanonevar.input_ -> stopifnot
Execution halted
